FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.9-buster

RUN python3 --version && pip3 --version

COPY requirements.txt .
RUN pip3 install -r requirements.txt

WORKDIR /usr/src/app

# VOLUME ["/opt/vc"]

COPY scripts .

CMD ["sh", "start.sh"]
