FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.9-buster

RUN python3 --version && pip3 --version

RUN pip3 install picamera

WORKDIR /usr/src/app

# VOLUME ["/opt/vc"]

COPY scripts .

CMD ["sh", "start.sh"]
